In [2]:
import pandas as pd

In [3]:
fuel_econ_5600 = pd.read_html('https://en.wikipedia.org/wiki/Fuel_economy_in_aircraft',header=0)[0]

In [4]:
fuel_econ_5600

,Model,First flight,Seats,Fuel burn,Fuel per seat
0,ATR 42-500,1995,48,1.26 kg/km (4.5 lb/mi),3.15 L/100 km (75 mpg‑US)[26]
1,ATR 72-500,1997,70,1.42 kg/km (5.0 lb/mi),2.53 L/100 km (93 mpg‑US)[26]
2,Beechcraft 1900D (226 nm),1982,19,1.00 kg/km (3.56 lb/mi),6.57 L/100 km (35.8 mpg‑US)[27]
3,Bombardier Dash 8 Q400,1998,78,2.16 kg/km (7.7 lb/mi),3.46 L/100 km (68.0 mpg‑US)[28]
4,Dornier 228,1981,19,0.94 kg/km (3.3 lb/mi),6.22 L/100 km (37.8 mpg‑US)[29]
5,Dornier 328,1991,30,1.10 kg/km (3.91 lb/mi),4.57 L/100 km (51.5 mpg‑US)[30]
6,Embraer Brasilia,1983,30,0.92 kg/km (3.3 lb/mi),3.82 L/100 km (61.6 mpg‑US)[31]
7,Pilatus PC-12 (500 nm),1991,9,0.41 kg/km (1.5 lb/mi),5.66 L/100 km (41.6 mpg‑US)[32]
8,Saab 340,1983,32,1.1 kg/km (3.9 lb/mi),4.29 L/100 km (54.8 mpg‑US)[33]
9,Saab 2000,1992,50,1.75 kg/km (6.2 lb/mi),4.39 L/100 km (53.6 mpg‑US)[34]
10,Xian MA700,2019,68–86,1.69 kg/km (6.0 lb/mi),3.1–2.45 L/100 km (76–96 mpg‑US)[35]

In [5]:
df_fuel.drop(['First flight', 'Seats', 'Sector'], axis = 1, inplace=True)
df_fuel.columns = ['Model', 'Fuel burn', 'Fuel per seat']
df_fuel['Model'] = df_fuel['Model'].str.replace('\s\(.*\)', '')
df_fuel['Fuel burn'] = df_fuel['Fuel burn'].str.extract('(\d+.\d+)', expand=False ).astype(float)
df_fuel['Fuel per seat'] = df_fuel['Fuel per seat'].str.extract('(\d+.\d+)', expand=False).astype(float)

ValueError: labels ['Sector'] not contained in axis

In [9]:
def clean_fuel_econ(i):
    df_fuel = pd.read_html('https://en.wikipedia.org/wiki/Fuel_economy_in_aircraft',header=0)[i]
    try:
        df_fuel.drop(['First flight', 'Seats', 'Sector'], axis = 1, inplace=True)
    except ValueError:
        df_fuel.drop(['First flight', 'Seats'], axis = 1, inplace=True)
    df_fuel.columns = ['Model', 'Fuel burn', 'Fuel per seat']
    df_fuel['Model'] = df_fuel['Model'].str.replace('\s\(.*\)', '')
    df_fuel['Fuel burn'] = df_fuel['Fuel burn'].str.extract('(\d+.\d+)', expand=False ).astype(float)
    df_fuel['Fuel per seat'] = df_fuel['Fuel per seat'].str.extract('(\d+.\d+)', expand=False).astype(float)
    return df_fuel

In [17]:
a = clean_fuel_econ(4)
a

                 Model  Fuel burn  Fuel per seat
0      Airbus A330-200       6.40           3.32
1   Airbus A330neo-800       5.45           2.75
2   Airbus A330neo-900       5.94           2.48
3      Airbus A340-300       7.32           3.49
4      Airbus A350-900       6.03           2.39
5      Airbus A350-900       7.07           2.81
6          Airbus A380      13.78           3.27
7          Airbus A380      13.78           3.16
8       Boeing 747-400      11.11           3.34
9         Boeing 747-8      10.54           2.82
10        Boeing 747-8      10.90           3.35
11    Boeing 777-200ER       7.42           3.08
12    Boeing 777-200ER       7.44           3.09
13    Boeing 777-200LR       7.57           3.25
14    Boeing 777-300ER       8.49           2.91
15    Boeing 777-300ER       8.58           3.11
16       Boeing 777-9X       9.04           2.85
17        Boeing 787-8       5.38           2.77
18        Boeing 787-9       5.85           2.49
19        Boeing 787-9       5.63           2.31
20        Boeing 787-9       7.18           3.08